### PR TITLE
Fedora support

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
Unfortunately, our package names don't match.

**Comment by hroncok** [comment]
Will amend some stuff to readme, do not merge yet.

**Comment by hroncok** [comment]
done

**Comment by honzajavorek** [comment]
Thanks! I commented under the [other PR](https://github.com/honzajavorek/cartoonist/pull/2#issuecomment-205885895).

**Comment by honzajavorek** [comment]
Closed by #6.

**Pull request closed without merging**
