### PR TITLE
Fedora installation + progress messages in test script

### PR DESCRIPTION
**Pull request by oskopek**

### CODE REVIEW

**Comment by hroncok** [comment]
Oh, sorry, I didn't notice you added Fedora support. Fedora now uses dnf, not yum BTW.

**Comment by oskopek** [comment]
Yes, you're right. But people might want to run this on older versions of Fedora too -- and the yum command is still provided by newer Fedora versions for backwards compatibility.

**Comment by hroncok** [comment]
We should encourage people to use supported versions of Fedora :)

**Comment by honzajavorek** [comment]
Well from my point of view as a project maintainer, more supported systems / package managers means more installations of the project and more happy users, so I'm :+1: for including both ways.

**Comment by honzajavorek** [comment]
@hroncok @oskopek I love both your contributions. Do you guys think you could merge this somehow into a single PR? It would be awesome if the joint PR would:
- keep the [`echo` line](https://github.com/honzajavorek/cartoonist/pull/2/files#diff-1b531c5e405e0bc95890d52cf2f2f5b5R6) in tests
- use `dnf` if it's present, otherwise `yum` (or whatever way would be the best to keep backwards compatibility)

And thanks, really! This is really really awesome! :balloon: I'm sorry I didn't get to this earlier, but you know, hobby projects :sweat_smile:

**Comment by oskopek** [comment]
Closing this PR, will open a new one with the two PRs merged.

**Comment by hroncok** [comment]
Need some help?

**Pull request closed without merging**
